version: "3.7"
services:
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"

  server:
    container_name: server
    image: openjdk:11
    ports:
      - "8080:8080"
    command:
      - java
      - -jar
      - httpclient-with-boot-0.0.1-SNAPSHOT.jar
    working_dir: /usr/src/myapp/target
    volumes:
      - ./:/usr/src/myapp
